passwd:
  users:
    - name: takekazu
      ssh_authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDZ8dbPwGM2Ktf1puWfMTjdoglAkmZfaWZNCdfOJPfVT"
      groups: [ sudo, docker ]
storage:
  files:
    - path: /opt/bin/docker-compose
      filesystem: root
      mode: 0755
      contents:
        remote:
          url: https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64
          verification:
            hash:
              function: sha512
              sum: 3ff1145fa36057aca7073f90079e04e948723fda4da240b83bfcfe39c54eb218402c09d2a510a0b192620ebb69acd9a3ae6172c704915172232eb5fa0c2c0359
systemd:
  units:
    - name: docker.service
      enabled: true

# https://kinvolk.io/docs/flatcar-container-linux/latest/setup/releases/update-strategies/#auto-updates-with-a-maintenance-window
locksmith:
  reboot_strategy: reboot
  window_start: Thu 04:00
  window_length: 1h
